name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        emacs_version:
          - emacs-26-alpine-ci-eask
          - emacs-27-alpine-ci-eask
          - emacs-28-alpine-ci-eask
          - emacs-29-alpine-ci-eask
          - emacs-master-alpine-ci-eask
    runs-on: ${{ matrix.emacs_version }}
    steps:
      - uses: actions/checkout@v3
      - name: "Execute Eask CI"
        run: make ci
